### ISSUE TITLE
GraphPPL creates global random variable for temporary local random variables

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/GraphPPL.jl#21]
The following code in the `@model` macro

```julia
for n in 1:N
      ...
      u[k] ~ MvNormal(mean = m_u[k], cov = V_u[k])
      x[k] ~ MvNormal(mean = m_x[k], cov = V_x[k])
      tmp ~ u[k] + x[k]
      ...
 end
```

Creates a single huge `tmp` variable with a huge equality nodes chain connecting all random variables in the model (and potentially creating many loops in the model). In fact, I simply want to create an intermediate variable and discard it immediately. This probably has been introduced in #12 .

Its interesting though, it might be considered as a bug and as a feature at the same time. Depends on how you interpret this expression. There is nothing wrong with creating one single huge global variable `tmp` for all nodes. I would, however, resort to the `create+discard` behaviour in this case as it seems more natural to me.

![photo_2022-11-09 12 17 02](https://user-images.githubusercontent.com/6557701/200816417-fd601742-f54d-4965-a1e2-63f81a580c83.jpeg)

WDYT: @albertpod @bartvanerp @ismailsenoz @bertdv 

P.S. The workaround is quite trivial:

```julia
tmp = randomvar(N)

for n in 1:N
      ...
      u[k] ~ MvNormal(mean = m_u[k], cov = V_u[k])
      x[k] ~ MvNormal(mean = m_x[k], cov = V_x[k])
      tmp[k] ~ u[k] + x[k]
      ...
 end
```

**Comment by bvdmitri** [comment]
We could to smth like

```
for n in 1:N
      ...
      u[k] ~ MvNormal(mean = m_u[k], cov = V_u[k])
      x[k] ~ MvNormal(mean = m_x[k], cov = V_x[k])
      local tmp ~ u[k] + x[k]
      ...
 end
```

**Comment by bartvanerp** [comment]
Interesting bug/feature. Never considered it this way and I am also not sure what the most desirable approach would be. I can imagine that we alternatively could throw a warning if a variable is assigned multiple times. This would generally only throw warnings when dealing with goal priors.

**Comment by bertdv** [comment]
The current behavior is just plain wrong, because it forces $u[1] + x[1] = u[2] + x[2] = \ldots = u[k] + x[k]$, which is not what you want. 

The problem is really that `~` is not well-defined. The problem is that `~` is sometimes interpreted as `is distributed as`, and sometimes as `is assigned`. You really want to write: 

```
tmp = u[k] + x[k]
```

which should lead to (what you call) the desired behaviorm, namely assigning $u[k] + x[k]$ to `tmp`, no matter what the previous value of `tmp` is.

Unfortunately, as I understood (maybe I m wrong), you cannot do that because you cannot use the assignment operator `=` for a `randomvar`. 

There are two solutions. You shouls re-evaluate the meaning of `randomvar` and ponder if you really need that concept. After all, `tmp` is likely just a `float64`, and the assignment `=` should work for a `float64`.  The concept of a `random float64` is nonsense. It's a `float64` or not.

Alternatively, you may consider `:=` for assignment for a `randomvar`. then you get:
```
tmp := u[k] + x[k]
```

which is also uniquely interpretable. 

Last option would be to require end users to write
```
tmp[k] ~ u[k] + x[k]
```

But I think it is far from desired as it will lead to many end users writing wrong code. 

This is a big issue IMO.

**Comment by bvdmitri** [comment]
@bertdv 

- First, the issue has nothing to do with `+`, so `tmp = u[k] + x[k]` or `tmp := u[k] + x[k]` is not really a solution. I used `+` as an example, but the following code also does not behave as you would expect (though I actually didn't check it, will check it later):

```julia
for k in 1:N
    tau[k] ~ Gamma(...)
    mean[k] ~ Normal(...)
    tmp ~ Normal(mean[k], tau[k])
end
```

This code would create a global `tmp` variable as well. I should have been more clear on that in my description.

- Second, `tmp` is not `Float64`, `tmp` is a `RandomVariable` with unknown value/distribution at **model parsing** time. There is no way to determine the distribution or its value at parse time (during `@model` macro execution).

- Third, this code is actually behaves exactly as it "should", it just counterintuitive. `~` has a pretty well defined behaviour in the `GraphPPL.jl`. Expression of the form `r ~ p(x, y, z)` simply adds `p(r, x, y, z)` factor to the model's `p`. So in a sense, the GraphPPL.jl creates the following model:

$$
p(\text{tmp}, \textbf{u}, \textbf{x}, \dots) = \prod_{k = 1}^{N} p_k(\text{tmp}, u_k, x_k) \times \cdots
$$

while, indeed, the following model would be more intuitive:

$$
p(\textbf{tmp}, \textbf{u}, \textbf{x}, \dots) = \prod_{k = 1}^{N} p_k(\text{tmp}_k, u_k, x_k) \times \cdots
$$

It is a problem both in case if `p_k` is a _deterministic_ factor as `+` or stochastic as `Normal`. I would prefer the second case. The question is do we want the current behaviour to work as well?

**Comment by bertdv** [comment]
As we discussed, it would be better to write
```
t := u[k] + x[k]
```
for assignments. And keep the `~` for when the RHS specifies explicitly a probability distribution. 

There is another problem with the setup. If you would draw arrows in the graphs in the generative direction, then you find that the code does not correspond to a generative model. Proper code for the LHS generative model is (there are also other working variants):

```julia
tmp ~ MvNormal( ... )  
for k in 1:N
      ...
      u[k] ~ MvNormal(mean = m_u[k], cov = V_u[k])
      x[k] := tmp - u_k
      x[k] ~ MvNormal(mean = m_x[k], cov = V_x[k])
      ...
 end
```
This code should build the LHS graph. 

The RHS graph is simply
```julia
for k in 1:N
      ...
      u[k] ~ MvNormal(mean = m_u[k], cov = V_u[k])
      x[k] ~ MvNormal(mean = m_x[k], cov = V_x[k])
      tmp[k] := x[k] + u_k
      ...
 end
```

**Comment by bvdmitri** [comment]
@wouterwln We discussed this issue with you. I suggested to use `local` identifier as a possible solution.
